name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install gradle
        run: sudo snap install gradle

      - name: Lint, test and build the debug apk
        run: gradle check assembleDebug
