name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup java environment
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt

      - name: Lint, test and build the debug apk
        uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: current
          arguments: check assembleDebug