name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup java environment
        uses: joschi/setup-jdk@v2
        with:
          java-version: 11

      - name: Install gradle
        run: sudo snap install gradle --classic

      - name: Lint, test and build the debug apk
        run: gradle check assembleDebug --stacktrace
